steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/rama17-05-2020/rama-new/ramaapp:latest', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/rama17-05-2020/rama-new/ramaapp:latest']

  # Deploy to Cloud Run with specified service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rama-cloud-run'
      - '--image'
      - 'us-central1-docker.pkg.dev/rama17-05-2020/rama-new/ramaapp:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' 
      - '--port'
      - '9000'
      - '--service-account'
      - 'cloud-build@rama17-05-2020.iam.gserviceaccount.com'  # Replace with your service account email

images:
  - 'us-central1-docker.pkg.dev/rama17-05-2020/rama-new/ramaapp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
